# requires mod-md for LetsEncrypt

WSGIPythonPath /usr/local/src
WSGIRestrictStdout Off

MDomain environment.allsaintschelt.info
MDCertificateAgreement accepted

<VirtualHost *:80>
    ServerName environment.allsaintschelt.info
    Redirect permanent / https://environment.allsaintschelt.info/
</VirtualHost>

<VirtualHost *:443>

    ServerName neptune.vm.tornadovps.net
    ServerAlias environment.allsaintschelt.info
    ServerAdmin webmaster@neptune.vm.tornadovps.net

    SSLEngine On

    RewriteEngine On
    RewriteRule "^/$" "/index.html" [L]
    # dynamic part

    WSGIScriptAlias /rest /usr/local/src/web/application.wsgi
    WSGIDaemonProcess site.com processes=2 threads=15 display-name=%{GROUP}
    WSGIProcessGroup site.com

    <Directory /usr/local/src/web>
        Require all granted
    </Directory>


    # static part
    DocumentRoot /var/www/TempSensor
    Alias /favicon.ico /var/www/TempSensor/favicon.ico
    AliasMatch "^/((.+)\.(css|js|html))$" "/var/www/TempSensor/$1"
    <Directory /var/www/TempSensor>
        Require all granted
    </Directory>




    LogLevel info rewrite:trace2 wsgi:notice
    ErrorLog /var/log/tempsensor/httpd.log
    CustomLog /var/log/tempsensor//access.log combined
</VirtualHost>
