#!/bin/bash

systemctl apache2 stop

# config
a2disconf `ls conf-enabled`
rm /etc/apache2/conf-available/*
cp ./conf-available/*.conf /etc/apache2/conf-available
a2enconf *

# modules
apt install -y libapache2-mod-wsgi-py3
cp ./mods-available/alias.conf /etc/apache2/mods-available
a2enmod headers wsgi

# source
[[ -d /var/www/TempSensor ]] && mv /var/www/TempSensor /var/www/TempSensor.bak
tar xf dist.tgz
mv ./dist /var/www/TempSensor

[[ -d /opt/TempSensor ]] && mv /opt/TempSensor /opt/TempSensor.bak
tar xf wsgi.tgz
cp -r ../wsgi /opt/TempSensor

#sites
a2dissite `ls sites-enabled`
cp ./sites-available/*.site /etc/apache2/sites-available
a2ensite TempSensorVHOST.conf

systemctl apache2 start






